# Generated by Django 2.1.4 on 2019-04-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoalbum',
            old_name='User',
            new_name='user',
        ),
    ]
