# Generated by Django 2.1.4 on 2019-04-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20190408_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
